# Lenia world parameters
world_params:
  R: 13
  T: 10
  nb_channels: 1
  nb_dims: 3
  scale: 1.0
  get_state_fn_slug: v1
  weighted_average: true

# Lenia kernels parameters
kernels_params:
  k:
  - b: '1'
    c_in: 0
    c_out: 0
    gf_id: 0
    h: 1
    k_id: 0
    q: 4
    m: 0.15
    r: 1
    s: 0.015

# Parameters sampled by the QD algorithm.
genotype:
- domain:
  - 0.1
  - 0.6
  key: kernels_params.k.0.m
  type: float
- domain:
  - 0.0
  - 0.1
  key: kernels_params.k.0.s
  type: float

# Lenia properties used as a phenotype (parameters or behavioral statistics)
phenotype:
- kernels_params.k.0.m
- kernels_params.k.0.s

# Phenotypic grid against which Lenia are plot
grid:
  features_domain:
  - - 0.0
    - 1.0
  - - 0.0
    - 1.0
  shape:
  - 20
  - 20

# QD algorithm configuration
algo:
  batch_size: 4
  budget: 1024
  sampling_domain:
  - 0.0
  - 1.0
  mut_pb: 0.4
  sel_pb: 0.9
  sigma0: 0.5

# Generic search parameters
run_params:
  cells: MISSING
  code: dfa255f7-70ed-491c-a8f3-30f779355dd1
  max_run_iter: 1024
  nb_init_search: 64
  seed: 1

# Rendering parameters
render_params:
  pixel_border_size: 0
  pixel_size: 1
  pixel_size_power2: 1
  size_power2: 6
  world_size:
  - 64
  - 64
  - 64

# Generic configuration parameters
other:
  render_bests: true