defaults:
  - world_params: default
  - render_params: default
  - run_params: init_search

run_params:
  nb_init_search: 64
  max_run_iter: 1024

kernels_params:
  k:
    - b: '1, 0, 1/2'
      c_in: 0
      c_out: 0
      gf_id: 0
      h: 1
      k_id: 0
      m: 0.3770679299340973
      r: 1
      s: 0.06512496140859439