defaults:
  - world_params: default
  - render_params: default
  - kernels_params: default2
  - run_params: init_search

genotype:
  - key: kernels_params.k.0.r
    domain: 
      - 0.5
      - 1.5
    type: float
  # - key: kernels_params.k.0.b
  #   domain: 
  #     - "1"
  #     - "1,1"
  #     - "1,1,1"
  #   type: choice
  - key: kernels_params.k.0.m
    domain: 
      - 0.
      - 1.
    type: float
  - key: kernels_params.k.0.s
    domain: 
      - 0.
      - 1.
    type: float
  # - key: kernels_params.k.0.k_id
  #   domain: 
  #     - 0
  #     - 4
  #   type: int
  # - key: kernels_params.k.0.gf_id
  #   domain: 
  #     - 0
  #     - 2
  #   type: int
  - key: kernels_params.k.1.r
    domain: 
      - 0.5
      - 1.5
    type: float
  - key: kernels_params.k.1.m
    domain: 
      - 0.
      - 1.
    type: float
  - key: kernels_params.k.1.s
    domain: 
      - 0.
      - 1.
    type: float

phenotype:
  - kernels_params.k.0.m
  - kernels_params.k.0.s
  - kernels_params.k.1.m
  - kernels_params.k.1.s

grid:
  features_domain:
    - - 0.
      - 1.
    - - 0.
      - 1.
    - - 0.
      - 1.
    - - 0.
      - 1.
  shape: [10, 10, 10, 10]
  
algo:
  budget: 512
  ind_domain:
    - 0.
    - 1.
  # RandomSearchMut
  sel_pb: 0.9
  mut_pb: 0.25
  eta: 20
  # cmaes
  sigma0: 0.2
  separable_cma: false
  ignore_if_not_added_to_container: false

other:
  dump_bests: True