defaults:
  - world_params: default
  - render_params: default
  - run_params: default

world_params:
  update_fn_version: 'v1'
kernels_params:
  k:
    - k_id: 0
      q: 4
      r: 1
      b: '1'
      gf_id: 0
      m: 0.17
      s: 0.015
      h: 1
      c_in: 0
      c_out: 0
run_params:
  nb_init_search: 128
  max_run_iter: 1024

genotype:
  - key: world_params.T
    domain: 
      - 2.
      - 20.
    type: float
  - key: kernels_params.k.0.m
    domain: 
      - .1
      - .6
    type: float
  - key: kernels_params.k.0.s
    domain: 
      - 0.
      - .1
    type: float

phenotype:
  - behaviours.mass_density
  - behaviours.mass_speed

grid:
  features_domain:
    - - 0.
      - 1.
    - - 0.
      - 1.
  shape: [25, 25]
  
algo:
  # Generic
  budget: 4096
  batch_size: 16
  sampling_domain:
    - 0.
    - 1.
  # cmaes
  mut_sigma0: 0.01
  sigma0: 0.15

other:
  render_bests: True