defaults:
  - world_params: default
  - render_params: default
  - run_params: init_search

run_params:
  nb_init_search: 64
  max_run_iter: 1024

kernels_params:
  k:
    - r: 1
      b: '1'
      m: 0.15
      s: 0.015
      h: 1
      k_id: 0
      gf_id: 0
      c_in: 0
      c_out: 0