algo:
  batch_size: 4
  budget: 1024
  eta: 20.0
  ignore_if_not_added_to_container: false
  sampling_domain:
  - 0.0
  - 1.0
  initial_expected_rwds: 1.0
  mut_pb: 0.4
  sel_pb: 0.9
  separable_cma: false
  sigma0: 0.5
  zeta: 0.0005
genotype:
- domain:
  - 0.0
  - 1.0
  key: kernels_params.k.0.m
  type: float
- domain:
  - 0.0
  - 0.75
  key: kernels_params.k.0.s
  type: float
grid:
  features_domain:
  - - 0.0
    - 1.0
  - - 0.0
    - 0.75
  shape:
  - 20
  - 20
kernels_params:
  k:
  - b: '1'
    c_in: 0
    c_out: 0
    gf_id: 0
    h: 1
    k_id: 0
    q: 4
    m: 0.15
    r: 1
    s: 0.015
other:
  dump_bests: true
phenotype:
- kernels_params.k.0.m
- kernels_params.k.0.s
render_params:
  pixel_border_size: 0
  pixel_size: 1
  pixel_size_power2: 1
  size_power2: 7
  win_size_power2: 9
  world_size:
  - 128
  - 128
run_params:
  cells: MISSING
  code: dfa255f7-70ed-491c-a8f3-30f779355dd1
  max_run_iter: 1024
  nb_init_search: 64
  seed: 1
world_params:
  R: 13
  T: 10
  nb_channels: 1
  nb_dims: 2
